# fly.toml app configuration file for websocket-server-ancient-shape-3559
app = "websocket-server-ancient-shape-3559"
primary_region = "iad"

[machines]
  size = "shared-cpu-1x"

[deploy]
  strategy = "rolling"
  min_machines_running = 1

# This service handles HTTP requests on port 80 and redirects them to HTTPS.
[[services]]
  internal_port = 8080
  protocol = "tcp"
  processes = ["app"]
 
  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

# This service handles secure WebSocket (WSS) and HTTPS traffic on port 443.
[[services]]
  internal_port = 8080
  protocol = "tcp"
  processes = ["app"]

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]
  
  [[services.checks]]
    type = "http"
    interval = "10s"
    timeout = "5s"
    grace_period = "20s"
    method = "get"
    path = "/health"
    protocol = "http"
    port = 8080

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"